/*
 * rle_utils.c — Shared utilities for the conversion tools
 *
 * SPDX-License-Identifier: MIT
 */

#include "rle_utils.h"

#include <inttypes.h>
#include <string.h>

int write_rle_header(FILE       *out,
                     const char  *array_name,
                     const char  *source_name,
                     int          width,
                     int          height,
                     const uint8_t *rle_data,
                     size_t       rle_size,
                     size_t       raw_size)
{
    size_t i;

    if ((out == NULL) || (array_name == NULL) || (rle_data == NULL)) {
        return -1;
    }

    fprintf(out,
            "/*\n"
            " * Auto-generated by rgb565-rle converter.\n"
            " * Source: %s\n"
            " * Dimensions: %d × %d\n"
            " * Raw size: %zu bytes, Compressed: %zu bytes (%.1f%%)\n"
            " */\n\n",
            source_name ? source_name : "(unknown)",
            width, height,
            raw_size, rle_size,
            raw_size > 0u
                ? (double)rle_size / (double)raw_size * 100.0
                : 0.0);

    fprintf(out,
            "#include <stdint.h>\n\n");

    fprintf(out,
            "#define %s_WIDTH  %d\n"
            "#define %s_HEIGHT %d\n"
            "#define %s_PIXELS %d\n"
            "#define %s_RLE_SIZE %zuu\n\n",
            array_name, width,
            array_name, height,
            array_name, width * height,
            array_name, rle_size);

    fprintf(out,
            "static const uint8_t %s[%zu] = {\n",
            array_name, rle_size);

    for (i = 0u; i < rle_size; i++) {
        if ((i & 0x0Fu) == 0u) {
            fputs("    ", out);
        }
        fprintf(out, "0x%02X", (unsigned int)rle_data[i]);
        if (i + 1u < rle_size) {
            fputc(',', out);
        }
        if ((i & 0x0Fu) == 0x0Fu) {
            fputc('\n', out);
        } else if (i + 1u < rle_size) {
            fputc(' ', out);
        }
    }

    if ((rle_size & 0x0Fu) != 0u) {
        fputc('\n', out);
    }

    fprintf(out, "};\n");
    return 0;
}

int write_rle_binary(FILE *out, const uint8_t *rle_data, size_t rle_size)
{
    if ((out == NULL) || (rle_data == NULL)) {
        return -1;
    }

    if (fwrite(rle_data, 1u, rle_size, out) != rle_size) {
        return -1;
    }

    return 0;
}

void print_size_comparison(const char *label,
                           size_t raw_bytes,
                           size_t compressed_bytes)
{
    double ratio;

    ratio = (raw_bytes > 0u)
                ? (double)compressed_bytes / (double)raw_bytes * 100.0
                : 0.0;

    printf("  %-24s  raw: %10zu B  compressed: %10zu B  (%5.1f%%",
           label, raw_bytes, compressed_bytes, ratio);

    if (compressed_bytes < raw_bytes) {
        printf(", %5.1f%% saving", 100.0 - ratio);
    } else if (compressed_bytes > raw_bytes) {
        printf(", EXPANDED by %.1f%%", ratio - 100.0);
    }

    printf(")\n");
}
