/*
 * video2rle — Convert a video (image sequence or raw frames) to RLE format
 *
 * Input modes:
 *   Sequence: video2rle [options] frame_0001.png frame_0002.png ...
 *   Raw:      video2rle [options] --raw <file> --width W --height H
 *             (file contains concatenated raw RGB565 frames)
 *
 * Output modes:
 *   .h    C header with per-frame RLE arrays + frame-offset table
 *   .bin  Binary container: [frame_count:4][offsets[]][frame_data...]
 *
 * Options:
 *   -o <file>     Output file path (default: output.rle.h or output.rle.bin)
 *   -t h          Output as C header  (default)
 *   -t bin        Output as raw binary container
 *   -n <name>     Base array name for C header (default: "video")
 *   -w <width>    Frame width  (required for raw mode)
 *   -h <height>   Frame height (required for raw mode)
 *   --raw         Input is a single raw RGB565 file
 *   --help        Show this help
 *
 * Dependencies: stb_image.h (for image-sequence mode)
 *
 * SPDX-License-Identifier: MIT
 */

#include <stdint.h>
#include <stdio.h>
#include <stdlib.h>
#include <string.h>

#define STBI_NO_HDR
#define STBI_NO_LINEAR
#define STB_IMAGE_IMPLEMENTATION
#include "stb_image.h"

#include "rgb565_rle.h"
#include "rle_utils.h"

/* --------------------------------------------------------------------------
 * RGB888→RGB565 conversion
 * -------------------------------------------------------------------------- */

static uint16_t rgb888_to_rgb565(uint8_t r, uint8_t g, uint8_t b)
{
    uint16_t r5 = ((uint16_t)r * 31u + 127u) / 255u;
    uint16_t g6 = ((uint16_t)g * 63u + 127u) / 255u;
    uint16_t b5 = ((uint16_t)b * 31u + 127u) / 255u;
    return (uint16_t)((r5 << 11) | (g6 << 5) | b5);
}

static uint16_t *rgba_to_rgb565(const uint8_t *src,
                                int sw, int sh,
                                int dw, int dh)
{
    uint16_t *dst;
    int       x, y;

    dst = (uint16_t *)malloc((size_t)(dw * dh) * sizeof(uint16_t));
    if (dst == NULL) return NULL;

    for (y = 0; y < dh; y++) {
        int sy = (sh > 0) ? (y * sh / dh) : 0;
        for (x = 0; x < dw; x++) {
            int     sx  = (sw > 0) ? (x * sw / dw) : 0;
            int     idx = (sy * sw + sx) * 4;
            dst[y * dw + x] = rgb888_to_rgb565(
                src[idx + 0u], src[idx + 1u], src[idx + 2u]);
        }
    }
    return dst;
}

/* --------------------------------------------------------------------------
 * Container format (.bin)
 *
 *   [uint32_t frame_count  (LE)]
 *   [uint32_t offsets[N+1] (LE)]   -- offset[N] = total file size
 *   [frame 0 RLE stream]
 *   [frame 1 RLE stream]
 *   ...
 *
 * Each frame's RLE stream is the standard 4-byte-pixel_count-header + body
 * format produced by rgb565_rle_compress().
 * -------------------------------------------------------------------------- */

/* --------------------------------------------------------------------------
 * Write C header for video
 * -------------------------------------------------------------------------- */

static int write_video_header(FILE          *out,
                              const char     *base_name,
                              int             width,
                              int             height,
                              uint8_t       **frame_data,
                              const size_t   *frame_sizes,
                              size_t          total_raw,
                              int             frame_count)
{
    int    f;
    size_t total_comp = 0u;
    size_t i;

    for (f = 0; f < frame_count; f++) {
        total_comp += frame_sizes[f];
    }

    fprintf(out,
            "/*\n"
            " * Auto-generated by video2rle (rgb565-rle).\n"
            " * Frames: %d,  Dimensions: %d × %d\n"
            " * Raw total: %zu bytes,  Compressed total: %zu bytes"
            " (%.1f%%)\n"
            " */\n\n",
            frame_count, width, height,
            total_raw, total_comp,
            total_raw > 0u
                ? (double)total_comp / (double)total_raw * 100.0
                : 0.0);

    fprintf(out,
            "#include <stdint.h>\n\n");

    fprintf(out,
            "#define %s_WIDTH       %d\n"
            "#define %s_HEIGHT      %d\n"
            "#define %s_PIXELS      %d\n"
            "#define %s_FRAME_COUNT %d\n"
            "#define %s_TOTAL_SIZE  %zuu\n\n",
            base_name, width,
            base_name, height,
            base_name, width * height,
            base_name, frame_count,
            base_name, total_comp);

    /* offset table */
    fprintf(out,
            "/* Byte offset of each frame in %s_FRAMES[] */\n",
            base_name);
    fprintf(out,
            "static const uint32_t %s_FRAME_OFFSETS[%d+1] = {\n",
            base_name, frame_count);

    {
        size_t off = 0u;

        for (f = 0; f <= frame_count; f++) {
            fprintf(out, "    %zuu", off);
            if (f < frame_count) {
                off += frame_sizes[f];
                fputs(",\n", out);
            } else {
                fputs("\n", out);
            }
        }
    }
    fprintf(out, "};\n\n");

    /* concatenated frame data */
    fprintf(out,
            "/* Concatenated RLE frames %s_FRAMES */\n",
            base_name);
    fprintf(out,
            "static const uint8_t %s_FRAMES[%zu] = {\n",
            base_name, total_comp);

    {
        size_t global_idx = 0u;

        for (f = 0; f < frame_count; f++) {
            fprintf(out, "    /* --- frame %d --- */\n", f);

            for (i = 0u; i < frame_sizes[f]; i++) {
                if ((global_idx & 0x0Fu) == 0u) {
                    fputs("    ", out);
                }
                fprintf(out, "0x%02X",
                        (unsigned int)frame_data[f][i]);
                global_idx++;
                if (global_idx < total_comp) {
                    fputc(',', out);
                }
                if ((global_idx & 0x0Fu) == 0x0Fu) {
                    fputc('\n', out);
                } else if (global_idx < total_comp) {
                    fputc(' ', out);
                }
            }
            if ((global_idx & 0x0Fu) != 0u && f + 1 < frame_count) {
                fputc('\n', out);
            }
            /* also end frame comment block with newline */
            if (f + 1 < frame_count
                && (global_idx & 0x0Fu) != 0u) {
                /* already had newline above */;
            } else if (f + 1 < frame_count) {
                /* end of exactly 16-byte line, add a bit of
                 * separation anyway */
            }
        }

        if ((global_idx & 0x0Fu) != 0u) {
            fputc('\n', out);
        }
    }

    fprintf(out, "};\n");
    return 0;
}

/* --------------------------------------------------------------------------
 * Write binary container
 * -------------------------------------------------------------------------- */

static int write_video_binary(FILE        *out,
                              uint8_t     **frame_data,
                              const size_t *frame_sizes,
                              int           frame_count)
{
    int    f;
    size_t total_comp = 0u;
    size_t off;

    /* compute offsets */
    {
        uint32_t offset = (uint32_t)(
            4u + (size_t)(frame_count + 1) * 4u);

        /* frame count */
        {
            uint32_t fc = (uint32_t)frame_count;
            fwrite(&fc, 4u, 1u, out);
        }

        /* offsets[0..frame_count] */
        fwrite(&offset, 4u, 1u, out);  /* offset[0] */
        for (f = 0; f < frame_count; f++) {
            offset += (uint32_t)frame_sizes[f];
            fwrite(&offset, 4u, 1u, out);
        }

        /* frame data */
        for (f = 0; f < frame_count; f++) {
            if (fwrite(frame_data[f], 1u,
                       frame_sizes[f], out) != frame_sizes[f]) {
                return -1;
            }
            total_comp += frame_sizes[f];
        }
    }

    (void)total_comp;
    return 0;
}

/* --------------------------------------------------------------------------
 * Compress one frame from RGB565 pixels, return malloc'd RLE buffer
 * -------------------------------------------------------------------------- */

static uint8_t *compress_frame(const uint16_t *pixels,
                               size_t pixel_count,
                               size_t *out_size)
{
    size_t   max_sz;
    uint8_t *rle;

    max_sz = rgb565_rle_max_compressed_size(pixel_count);
    if (max_sz == 0u) return NULL;

    rle = (uint8_t *)malloc(max_sz);
    if (rle == NULL) return NULL;

    *out_size = rgb565_rle_compress(pixels, pixel_count, rle, max_sz);
    if (*out_size == 0u) {
        free(rle);
        return NULL;
    }

    return rle;
}

/* --------------------------------------------------------------------------
 * Usage
 * -------------------------------------------------------------------------- */

static void print_usage(const char *prog)
{
    printf("Usage:\n");
    printf("  %s [options] frame_0001.png frame_0002.png ...\n", prog);
    printf("  %s [options] --raw <file> -w <W> -h <H>\n\n", prog);
    printf("Options:\n");
    printf("  -o <file>    Output file (default: output.rle.h / output.rle.bin)\n");
    printf("  -t h         Output as C header  (default)\n");
    printf("  -t bin       Output as raw binary container\n");
    printf("  -n <name>    Base array name for C header (default: \"video\")\n");
    printf("  -w <width>   Frame width  (required for --raw)\n");
    printf("  -h <height>  Frame height (required for --raw)\n");
    printf("  --raw        Input is a single raw RGB565 file\n");
    printf("  --help       Show this help\n");
}

/* ==========================================================================
 * Main
 * ========================================================================== */

int main(int argc, char **argv)
{
    const char *output_path  = NULL;
    const char *array_name   = "video";
    int         out_header   = 1;
    int         raw_mode     = 0;
    const char *raw_file     = NULL;
    int         req_w        = 0;
    int         req_h        = 0;
    int         i;

    /* arrays for per-frame compressed data */
    uint8_t   **frame_data = NULL;
    size_t     *frame_sizes = NULL;
    int         frame_count = 0;
    size_t      total_raw   = 0u;
    size_t      total_comp  = 0u;

    FILE       *fp         = NULL;
    int         ret        = EXIT_FAILURE;

    char        path_buf[512];

    /* --- two-pass argument parsing ---
     * Pass 1: scan for options (can appear anywhere).
     * Pass 2: collect positional (non-option) arguments as frame files.
     *          In --raw mode the first positional is the raw file.
     */
    {
        int arg;

        /* Pass 1 — options */
        for (arg = 1; arg < argc; arg++) {
            if (strcmp(argv[arg], "--help") == 0) {
                print_usage(argv[0]);
                return EXIT_SUCCESS;
            } else if (strcmp(argv[arg], "--raw") == 0) {
                raw_mode = 1;
            }
        }
        for (arg = 1; arg < argc; arg++) {
            if (strcmp(argv[arg], "-o") == 0 && (arg + 1 < argc)) {
                output_path = argv[arg + 1];
            } else if (strcmp(argv[arg], "-t") == 0 && (arg + 1 < argc)) {
                const char *t = argv[arg + 1];
                if (strcmp(t, "bin") == 0) out_header = 0;
                else if (strcmp(t, "h") == 0) out_header = 1;
                else {
                    fprintf(stderr, "Error: unknown type '%s'.\n", t);
                    return EXIT_FAILURE;
                }
            } else if (strcmp(argv[arg], "-n") == 0 && (arg + 1 < argc)) {
                array_name = argv[arg + 1];
            } else if (strcmp(argv[arg], "-w") == 0 && (arg + 1 < argc)) {
                req_w = atoi(argv[arg + 1]);
            } else if (strcmp(argv[arg], "-h") == 0 && (arg + 1 < argc)) {
                req_h = atoi(argv[arg + 1]);
            }
        }
    }

    /* Pass 2 — collect positional frame-file arguments */
    {
        const char **frame_files;
        int          max_frames;
        int          arg;

        max_frames  = argc;  /* upper bound */
        frame_files = (const char **)calloc((size_t)max_frames,
                                            sizeof(const char *));
        if (frame_files == NULL) {
            fprintf(stderr, "Error: memory allocation failed.\n");
            return EXIT_FAILURE;
        }

        for (arg = 1; arg < argc; arg++) {
            /* skip known option prefixes and their values */
            if (strcmp(argv[arg], "-o") == 0
                || strcmp(argv[arg], "-t") == 0
                || strcmp(argv[arg], "-n") == 0
                || strcmp(argv[arg], "-w") == 0
                || strcmp(argv[arg], "-h") == 0) {
                arg++;  /* skip value too */
                continue;
            }
            if (strcmp(argv[arg], "--raw") == 0
                || strcmp(argv[arg], "--help") == 0) {
                continue;
            }
            if (argv[arg][0] == '-') {
                fprintf(stderr, "Error: unknown option '%s'.\n",
                        argv[arg]);
                print_usage(argv[0]);
                free(frame_files);
                return EXIT_FAILURE;
            }
            frame_files[frame_count++] = argv[arg];
        }

        if (raw_mode && frame_count >= 1) {
            raw_file    = frame_files[0];
            frame_count = 0;  /* will be recalculated from raw data */
        }

        /* Process frame files (only image-sequence mode uses these) */
        {
        int f;

        if (!raw_mode && frame_count <= 0) {
            fprintf(stderr,
                    "Error: no input files specified.\n\n");
            print_usage(argv[0]);
            return EXIT_FAILURE;
        }

        if (raw_mode) {
            if (raw_file == NULL) {
                fprintf(stderr,
                        "Error: --raw requires an input file.\n");
                return EXIT_FAILURE;
            }
            if (req_w <= 0 || req_h <= 0) {
                fprintf(stderr,
                        "Error: --raw requires -w and -h.\n");
                return EXIT_FAILURE;
            }

            /* read raw RGB565 frames */
            {
                FILE    *rf;
                long     fsize;
                size_t   frame_bytes;
                uint8_t *raw_buf = NULL;

                rf = fopen(raw_file, "rb");
                if (rf == NULL) {
                    fprintf(stderr,
                            "Error: cannot open '%s'.\n",
                            raw_file);
                    return EXIT_FAILURE;
                }
                fseek(rf, 0L, SEEK_END);
                fsize = ftell(rf);
                fseek(rf, 0L, SEEK_SET);

                if (fsize <= 0L) {
                    fprintf(stderr,
                            "Error: '%s' is empty.\n",
                            raw_file);
                    fclose(rf);
                    return EXIT_FAILURE;
                }

                frame_bytes = (size_t)(req_w * req_h) * 2u;
                if ((size_t)fsize % frame_bytes != 0u) {
                    fprintf(stderr,
                            "Warning: file size (%ld) is not "
                            "a multiple of frame size (%zu); "
                            "trailing bytes ignored.\n",
                            fsize, frame_bytes);
                }

                frame_count = (int)((size_t)fsize / frame_bytes);
                if (frame_count <= 0) {
                    fprintf(stderr,
                            "Error: file too small for one frame.\n");
                    fclose(rf);
                    return EXIT_FAILURE;
                }

                frame_data  = (uint8_t **)calloc(
                    (size_t)frame_count, sizeof(uint8_t *));
                frame_sizes = (size_t *)calloc(
                    (size_t)frame_count, sizeof(size_t));
                if ((frame_data == NULL)
                    || (frame_sizes == NULL)) {
                    fclose(rf);
                    fprintf(stderr,
                            "Error: memory allocation failed.\n");
                    goto done;
                }

                raw_buf = (uint8_t *)malloc(frame_bytes);
                if (raw_buf == NULL) {
                    fclose(rf);
                    fprintf(stderr,
                            "Error: memory allocation failed.\n");
                    goto done;
                }

                for (f = 0; f < frame_count; f++) {
                    size_t px_count;

                    if (fread(raw_buf, 1u, frame_bytes, rf)
                        != frame_bytes) {
                        fprintf(stderr,
                                "Error: short read on frame %d.\n",
                                f);
                        fclose(rf);
                        free(raw_buf);
                        goto done;
                    }

                    px_count = (size_t)(req_w * req_h);
                    frame_data[f] = compress_frame(
                        (const uint16_t *)raw_buf,
                        px_count,
                        &frame_sizes[f]);

                    if (frame_data[f] == NULL) {
                        fprintf(stderr,
                                "Error: compression failed "
                                "for frame %d.\n", f);
                        fclose(rf);
                        free(raw_buf);
                        goto done;
                    }

                    total_raw   += frame_bytes;
                    total_comp  += frame_sizes[f];
                }

                free(raw_buf);
                fclose(rf);
            }
        } else {
            /* image-sequence mode */
            {
            int f;

            frame_data  = (uint8_t **)calloc(
                (size_t)frame_count, sizeof(uint8_t *));
            frame_sizes = (size_t *)calloc(
                (size_t)frame_count, sizeof(size_t));
            if ((frame_data == NULL)
                || (frame_sizes == NULL)) {
                fprintf(stderr,
                        "Error: memory allocation failed.\n");
                goto done;
            }

            for (f = 0; f < frame_count; f++) {
                const char *path = frame_files[f];
                int         iw, ih, ich;
                uint8_t    *img;
                uint16_t   *px;
                size_t      px_count;

                img = stbi_load(path, &iw, &ih, &ich, 4);
                if (img == NULL) {
                    fprintf(stderr,
                            "Error: cannot load '%s': %s\n",
                            path, stbi_failure_reason());
                    goto done;
                }

                if (f == 0) {
                    req_w = iw;
                    req_h = ih;
                }

                px = rgba_to_rgb565(img, iw, ih, req_w, req_h);
                stbi_image_free(img);

                if (px == NULL) {
                    fprintf(stderr,
                            "Error: conversion failed "
                            "for '%s'.\n", path);
                    goto done;
                }

                px_count = (size_t)(req_w * req_h);
                frame_data[f] = compress_frame(px, px_count,
                                               &frame_sizes[f]);
                free(px);

                if (frame_data[f] == NULL) {
                    fprintf(stderr,
                            "Error: compression failed "
                            "for frame %d.\n", f);
                    goto done;
                }

                total_raw  += px_count * 2u;
                total_comp += frame_sizes[f];
            }
            }  /* end image-sequence f-loop */
        }
        }  /* end process-frame-files block */

        free(frame_files);
    }  /* end two-pass parsing block */

    /* --- determine output path --- */
    if (output_path == NULL) {
        const char *ext = out_header ? ".rle.h" : ".rle.bin";
        snprintf(path_buf, sizeof(path_buf), "output%s", ext);
        output_path = path_buf;
    }

    /* --- write output --- */
    fp = fopen(output_path, "wb");
    if (fp == NULL) {
        fprintf(stderr, "Error: cannot open '%s' for writing.\n",
                output_path);
        goto done;
    }

    if (out_header) {
        if (write_video_header(fp, array_name,
                               req_w, req_h,
                               frame_data, frame_sizes,
                               total_raw, frame_count) != 0) {
            fprintf(stderr, "Error: failed to write header.\n");
            goto done;
        }
    } else {
        if (write_video_binary(fp,
                               frame_data, frame_sizes,
                               frame_count) != 0) {
            fprintf(stderr, "Error: failed to write binary.\n");
            goto done;
        }
    }

    fclose(fp);
    fp = NULL;

    /* --- summary --- */
    printf("\n");
    {
        char label[128];
        snprintf(label, sizeof(label),
                 "%d frames @ %d×%d",
                 frame_count, req_w, req_h);
        print_size_comparison(label, total_raw, total_comp);
    }
    printf("  Per-frame avg: raw %zu B,  compressed %zu B  "
           "(%.1f%%)\n",
           frame_count > 0 ? total_raw  / (size_t)frame_count : 0u,
           frame_count > 0 ? total_comp / (size_t)frame_count : 0u,
           total_raw > 0u
               ? (double)total_comp / (double)total_raw * 100.0
               : 0.0);
    printf("  Output: %s  (%s)\n",
           output_path, out_header ? "C header" : "binary");
    printf("\n");

    ret = EXIT_SUCCESS;

done:
    if (fp != NULL) fclose(fp);

    if (frame_data != NULL) {
        int f;
        for (f = 0; f < frame_count; f++) {
            free(frame_data[f]);
        }
        free(frame_data);
    }
    free(frame_sizes);

    return ret;
}
